#  Copyright (c) 2020.  This repo or code maintained  by Sanjay kranthi
#  you can contact on this mail: kranthi0987@gmail.com
#  you can clone my projects git: github.com/kranthi0987

# Generated by Django 3.0.4 on 2020-03-29 11:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelData',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d937628b-0ade-465b-ae60-10131061498c'), primary_key=True, serialize=False)),
                ('real_name', models.TextField()),
                ('tz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriodModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(blank=True, db_column='purchase', null=True, on_delete=django.db.models.deletion.CASCADE, to='testData.UserModelData')),
            ],
        ),
    ]
