# Generated by Django 3.0.4 on 2020-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testData', '0002_auto_20200329_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodeldata',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
