#  Copyright (c) 2020.  This repo or code maintained  by Sanjay kranthi
#  you can contact on this mail: kranthi0987@gmail.com
#  you can clone my projects git: github.com/kranthi0987

# Generated by Django 3.0.4 on 2020-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testData', '0003_auto_20200329_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodeldata',
            name='id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
    ]
