# Generated by Django 3.0.4 on 2020-03-29 15:09

import apps.testData.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testData', '0004_auto_20200329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodeldata',
            name='id',
            field=models.CharField(default=apps.testData.models.my_random_string, max_length=50, primary_key=True, serialize=False),
        ),
    ]
