#  Copyright (c) 2020.  This repo or code maintained  by Sanjay kranthi
#  you can contact on this mail: kranthi0987@gmail.com
#  you can clone my projects git: github.com/kranthi0987

# Generated by Django 3.0.4 on 2020-03-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testData', '0005_auto_20200329_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiodmodels',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='testData.UserModelData'),
        ),
    ]
